// Themen-Warteschlange für die automatisierte Guide-Generierung.
// Kuratiert nach echter Sammler-Such-Intention (Google: "pokemon karten ...").
// Der Cron arbeitet die Liste der Reihe nach ab — bereits generierte Slugs
// werden übersprungen. Neue Themen unten anhängen, Reihenfolge = Priorität.

export interface GuideTopic {
  slug: string;
  title: string;
  /** Icon-Key für <ContentIcon> (Lucide) — keine Emojis, siehe CLAUDE.md UI-Regeln */
  icon: string;
  badge: string;
  color: string;
  headerGradient: string;
  /** Such-Intention + inhaltlicher Auftrag an die Generierung. */
  brief: string;
  /** Grobe Sektions-Struktur als Leitplanke (die KI darf abweichen, nicht kürzen). */
  outline: string[];
}

export const GUIDE_TOPICS: GuideTopic[] = [
  {
    slug: 'pokemon-karten-verkaufen-wo-und-wie',
    title: 'Pokémon Karten verkaufen — wo und wie es wirklich funktioniert',
    icon: 'coins',
    badge: 'Verkaufen',
    color: 'emerald',
    headerGradient: 'from-emerald-800 to-green-950',
    brief: 'Suchintention: "pokemon karten verkaufen". Sammler wollen wissen, welche Plattform (Cardmarket, eBay, lokale Händler, Kleinanzeigen) sich wofür eignet, welche Gebühren anfallen, wie man Karten korrekt beschreibt/fotografiert und wie Versand sicher funktioniert. Neutral vergleichen, keine Verkaufsempfehlung für eine Plattform.',
    outline: ['Die Verkaufswege im Vergleich (Plattform-Mechanik, Gebührenlogik, Zielgruppe)', 'Zustand ehrlich einstufen — warum Überbewertung nach hinten losgeht', 'Fotos und Beschreibung, die Käufer überzeugen', 'Versand: Schutz, Nachweis, typische Fehler'],
  },
  {
    slug: 'was-ist-meine-pokemon-sammlung-wert',
    title: 'Was ist meine Pokémon-Sammlung wert? So findest du es systematisch heraus',
    icon: 'search',
    badge: 'Bewertung',
    color: 'violet',
    headerGradient: 'from-violet-800 to-indigo-900',
    brief: 'Suchintention: "pokemon karten wert herausfinden". Schritt-für-Schritt: Karten identifizieren (Set-Symbol, Nummer, Seltenheit), Preise auf Cardmarket nachschlagen, Zustand einordnen, typische Anfängerfehler (Massenkarten überschätzen). Verweis auf die Preissuche dieser Seite.',
    outline: ['Karte identifizieren: Set-Symbol, Kartennummer, Seltenheitszeichen', 'Preis nachschlagen: Cardmarket richtig lesen (Trend vs. Angebote)', 'Zustand einordnen — der größte Werthebel', 'Realistische Erwartung: warum die meisten Karten wenig wert sind'],
  },
  {
    slug: 'pokemon-erstauflage-erkennen-1st-edition',
    title: 'Erstauflage erkennen: 1st Edition, Shadowless & Unlimited unterscheiden',
    icon: 'medal',
    badge: 'Vintage',
    color: 'amber',
    headerGradient: 'from-amber-700 to-orange-900',
    brief: 'Suchintention: "pokemon 1st edition erkennen". Die Merkmale: 1st-Edition-Stempel, Shadowless-Merkmale beim Base Set, Unlimited-Unterschiede, deutsche vs. englische Auflagen. Nur dokumentierte, verifizierbare Merkmale (Bulbapedia als Quelle) — keine erfundenen Details.',
    outline: ['Der 1st-Edition-Stempel: wo er sitzt und wie er aussieht', 'Shadowless beim Base Set: die Merkmale im Detail', 'Unlimited und spätere Drucke unterscheiden', 'Deutsche Auflagen: was anders ist'],
  },
  {
    slug: 'psa-vs-cgc-vs-bgs-grading-vergleich',
    title: 'PSA vs. CGC vs. BGS: Die Grading-Anbieter im sachlichen Vergleich',
    icon: 'scale',
    badge: 'Grading',
    color: 'blue',
    headerGradient: 'from-blue-800 to-blue-950',
    brief: 'Suchintention: "psa oder cgc pokemon". Sachlicher Anbieter-Vergleich: Bewertungsskalen, Marktakzeptanz, Slab-Formate, typische Bearbeitungswege aus Deutschland. Keine Preisangaben (ändern sich) — auf die offiziellen Preisseiten verweisen. Keine Empfehlung, nur Kriterien.',
    outline: ['Die drei Anbieter und ihre Bewertungsphilosophie', 'Marktakzeptanz: wie der Sammlermarkt die Slabs behandelt', 'Ablauf aus Deutschland: Weg, Zoll, Wartezeit-Logik', 'Entscheidungskriterien je nach Kartentyp'],
  },
  {
    slug: 'booster-box-vs-etb-vs-einzelkarten',
    title: 'Booster Box, ETB oder Einzelkarten: Was die Produktformen unterscheidet',
    icon: 'package',
    badge: 'Produkte',
    color: 'indigo',
    headerGradient: 'from-indigo-800 to-indigo-950',
    brief: 'Suchintention: "pokemon booster box oder etb". Die Produktformen erklären: Display/Booster Box, Elite Trainer Box, Bundles, Tins, Einzelkarten. Inhalt, Pull-Logik, Sealed-Markt-Verhalten nach Produktionsende. Statistik: Packs öffnen vs. Direktkauf. Keine Kaufempfehlung.',
    outline: ['Die Produktformen und was drinsteckt', 'Die Statistik des Pack-Öffnens: Erwartungswert verstehen', 'Sealed nach Produktionsende: das dokumentierte Marktmuster', 'Welche Form zu welchem Sammlertyp passt — Kriterien statt Empfehlung'],
  },
  {
    slug: 'pokemon-karten-zustand-bewerten-nm-bis-poor',
    title: 'Kartenzustand bewerten: Von Near Mint bis Poor — das Cardmarket-System',
    icon: 'microscope',
    badge: 'Zustand',
    color: 'emerald',
    headerGradient: 'from-emerald-800 to-green-950',
    brief: 'Suchintention: "pokemon karten zustand near mint". Die Cardmarket-Zustandsstufen (MT/NM/EX/GD/LP/PL/PO) im Detail: worauf bei Ecken, Kanten, Oberfläche, Zentrierung achten. Wie sich Zustand auf den Marktwert auswirkt (qualitativ). Whitening, Kratzer, Knicke erkennen.',
    outline: ['Die Cardmarket-Skala von Mint bis Poor', 'Die vier Prüfzonen: Ecken, Kanten, Oberfläche, Zentrierung', 'Typische Schäden und wie man sie erkennt (Whitening, Clouding, Knicke)', 'Zustand und Marktwert: das Verhältnis verstehen'],
  },
  {
    slug: 'japanische-pokemon-karten-sammeln',
    title: 'Japanische Pokémon-Karten: Was Sammler über den JP-Markt wissen sollten',
    icon: 'map',
    badge: 'Japan',
    color: 'rose',
    headerGradient: 'from-rose-800 to-rose-950',
    brief: 'Suchintention: "japanische pokemon karten unterschied". Unterschiede JP vs. EN/DE: Druckqualität-Ruf, Set-Struktur (andere Set-Namen/-Nummern), Preisniveau-Struktur, Verfügbarkeit in Europa. Nur verifizierbare Fakten, Bulbapedia als Set-Quelle.',
    outline: ['Wie sich japanische Sets von westlichen unterscheiden', 'Druck und Verarbeitung: der Ruf japanischer Karten', 'Preisstruktur: warum JP-Karten oft anders notieren', 'Kaufwege in Europa und worauf beim Import zu achten ist'],
  },
  {
    slug: 'pokemon-karten-fuer-kinder-sammeln-eltern-guide',
    title: 'Pokémon-Karten fürs Kind: Der Eltern-Guide ohne Fachchinesisch',
    icon: 'users',
    badge: 'Eltern',
    color: 'violet',
    headerGradient: 'from-violet-800 to-indigo-900',
    brief: 'Suchintention: Eltern, deren Kind mit Pokémon-Karten anfängt. Was kaufen (Themendecks vs. Booster), was sind die Karten im Schulhof-Tausch "wert", wie teure Karten des Kindes schützen, Fälschungen auf Spielzeugmärkten erkennen. Zugänglich, kein Jargon ohne Erklärung.',
    outline: ['Der Einstieg: was ein Kind wirklich braucht', 'Schulhof-Tausch: faire Tauschregeln und Wert-Grundgefühl', 'Die erste teure Karte: schützen statt verbieten', 'Fälschungen im Spielwarenhandel erkennen'],
  },
  {
    slug: 'pokemon-sets-rotation-standard-format',
    title: 'Set-Rotation und Standard-Format: Warum Spielkarten an Wert verlieren können',
    icon: 'refresh',
    badge: 'Format',
    color: 'blue',
    headerGradient: 'from-blue-800 to-blue-950',
    brief: 'Suchintention: "pokemon rotation was passiert mit karten". Die jährliche Format-Rotation erklärt: Regulation Marks, was aus dem Standard fällt, wie sich das historisch auf Spieler-Karten vs. Sammler-Karten auswirkt. Limitless TCG als Quelle für Formatdaten.',
    outline: ['Wie die Rotation funktioniert: Regulation Marks lesen', 'Spielwert vs. Sammlerwert: zwei getrennte Märkte', 'Das dokumentierte Muster: Turnier-Karten nach der Rotation', 'Was Rotation für reine Sammler bedeutet: wenig'],
  },
  {
    slug: 'pokemon-promo-karten-verstehen',
    title: 'Promo-Karten verstehen: Black Star, Stempel und Event-Karten',
    icon: 'sparkles',
    badge: 'Promos',
    color: 'amber',
    headerGradient: 'from-amber-700 to-orange-900',
    brief: 'Suchintention: "pokemon promo karte wert". Was Promos sind (Black Star Promos, Stamped-Versionen, Event-/Turnier-Promos, Produkt-Beilagen), wie man sie identifiziert (Promo-Nummern), warum ihre Marktpreise stark streuen. Bulbapedia als Promo-Listen-Quelle.',
    outline: ['Die Promo-Kategorien und ihre Nummernsysteme', 'Identifizieren: Promo-Stern, Stempel, Set-Zugehörigkeit', 'Warum Promo-Preise so stark streuen', 'Dokumentierte Beispiele besonders gefragter Promos'],
  },
  {
    slug: 'pokemon-karten-versichern-dokumentieren',
    title: 'Sammlung dokumentieren und absichern: Inventar, Fotos, Versicherungsfragen',
    icon: 'folder',
    badge: 'Absicherung',
    color: 'emerald',
    headerGradient: 'from-emerald-800 to-green-950',
    brief: 'Suchintention: Sammler mit wachsendem Sammlungswert. Inventarliste führen (welche Daten pro Karte), Fotodokumentation, was Hausratversicherungen typischerweise abdecken (allgemein, keine Rechtsberatung — auf Versicherer verweisen), Portfolio-Tracker dieser Seite erwähnen.',
    outline: ['Das Minimal-Inventar: welche Daten pro Karte erfasst gehören', 'Fotodokumentation: was im Schadensfall zählt', 'Versicherungsfragen: was allgemein gilt und wen man fragt', 'Digitale Helfer: vom Spreadsheet zum Portfolio-Tracker'],
  },
  {
    slug: 'alte-pokemon-karten-1999-wert-check',
    title: 'Alte Pokémon-Karten von früher gefunden? Der systematische Wert-Check',
    icon: 'clock',
    badge: 'Vintage',
    color: 'amber',
    headerGradient: 'from-amber-700 to-orange-900',
    brief: 'Suchintention: "alte pokemon karten 1999 wert" — Dachbodenfund-Szenario. Systematisch prüfen: Welche Ära (Rückseiten-Design, Copyright-Zeile), welche Karten überhaupt Potenzial haben (Holos, Erstauflage), Zustand realistisch einschätzen, nächste Schritte. Erwartungsmanagement: die meisten Funde sind Massenware.',
    outline: ['Die Ära bestimmen: Copyright-Zeile und Set-Symbol lesen', 'Welche Karten aus alten Sammlungen Potenzial haben — und welche nicht', 'Zustand nach Jahren im Karton: realistisch bleiben', 'Die nächsten Schritte: prüfen, dokumentieren, bewerten lassen'],
  },
  // ── Erweiterung 27.09.2026 ─────────────────────────────────────────────────
  // Die Warteschlange war seit dem 08.09. leer — seitdem entstand kein Guide.
  // Guides sind die Evergreen-Einstiege aus der Google-Suche; die KI-Kosten
  // lagen bei 1,44 $ im Monat. Themen nach deutscher Suchintention, jede
  // Brief-Anweisung verbietet erfundene Zahlen ausdruecklich.
  {
    slug: "pokemon-karten-fake-erkennen",
    title: "Gefälschte Pokémon-Karten erkennen: Die Prüfungen, die wirklich funktionieren",
    icon: "shield",
    badge: "Echtheit",
    color: "rose",
    headerGradient: "from-rose-800 to-rose-950",
    brief: "Suchintention: \"pokemon karten fake erkennen\". Verifizierbare Prüfmerkmale: Druckbild und Schrift, Farbsättigung, Kartenstärke und Kern (Lichttest), Rückseite, Holo-Muster, Größe, Energiesymbole. Wo Fälschungen typischerweise angeboten werden. Keine erfundenen Einzelfälle, keine Preisangaben.",
    outline: ["Die schnellen Sichtprüfungen: Schrift, Farben, Rückseite", "Der Lichttest und die Kartenstärke", "Holo-Muster und Oberflächen, die Fälscher nicht nachbilden", "Wo Fälschungen auftauchen — und wie man sich beim Kauf absichert"],
  },
  {
    slug: "pokemon-karten-sortieren-sammlung-organisieren",
    title: "Pokémon-Karten sortieren: Systeme, mit denen eine Sammlung übersichtlich bleibt",
    icon: "folder",
    badge: "Organisation",
    color: "indigo",
    headerGradient: "from-indigo-800 to-indigo-950",
    brief: "Suchintention: \"pokemon karten sortieren\". Sortiersysteme im Vergleich: nach Set und Nummer, nach Pokédex, nach Typ, nach Wert. Wie man Duplikate, Massenkarten und wertvolle Karten trennt. Praktisch und ohne Produktempfehlung.",
    outline: ["Die vier gängigen Sortiersysteme und wofür sie taugen", "Set-Symbol und Kartennummer als Ordnungsgrundlage", "Massenkarten, Duplikate und wertvolle Karten trennen", "Eine Sammlung dokumentieren, damit der Überblick bleibt"],
  },
  {
    slug: "cardmarket-pokemon-karten-kaufen-anleitung",
    title: "Pokémon-Karten auf Cardmarket kaufen: Ablauf, Filter und Käuferschutz",
    icon: "search",
    badge: "Kaufen",
    color: "blue",
    headerGradient: "from-blue-800 to-blue-950",
    brief: "Suchintention: \"cardmarket pokemon kaufen\". Den Kaufablauf sachlich erklären: Suche und Filter (Sprache, Zustand, Land), Verkäuferbewertungen lesen, Versandoptionen, Warenkorb über mehrere Verkäufer, was bei Problemen gilt. Neutral, keine Kaufempfehlung, keine konkreten Gebührenbeträge (verweisen auf die Hilfeseiten von Cardmarket).",
    outline: ["Suche und Filter: Sprache, Zustand, Herkunftsland", "Verkäufer einschätzen: Bewertungen und Verkaufszahlen lesen", "Versandarten und warum sie bei teuren Karten zählen", "Wenn etwas schiefgeht: der Ablauf bei Problemen"],
  },
  {
    slug: "pokemon-karten-nummer-und-set-symbol-erklaert",
    title: "Kartennummer und Set-Symbol: So liest du jede Pokémon-Karte",
    icon: "book",
    badge: "Grundlagen",
    color: "violet",
    headerGradient: "from-violet-800 to-indigo-900",
    brief: "Suchintention: \"pokemon karten nummer bedeutung\". Wo Kartennummer, Setgröße, Set-Symbol, Seltenheitszeichen und Regulierungszeichen stehen und was sie bedeuten. Was Nummern über der Setgröße (z. B. 199/165) aussagen. Nur dokumentierte Merkmale, Bulbapedia als Quelle.",
    outline: ["Die Kartennummer und die Setgröße", "Das Set-Symbol und wo man es nachschlägt", "Seltenheitszeichen und Regulierungszeichen", "Nummern über der Setgröße: was sie verraten"],
  },
  {
    slug: "reverse-holo-und-holo-unterschied",
    title: "Holo, Reverse Holo, Full Art: Die Kartenvarianten auseinanderhalten",
    icon: "sparkles",
    badge: "Varianten",
    color: "violet",
    headerGradient: "from-violet-800 to-indigo-900",
    brief: "Suchintention: \"reverse holo pokemon\". Die Varianten erklären: normale Karte, Holo (Bild glänzt), Reverse Holo (Rahmen glänzt), Full Art, Textur-Karten. Wie man sie erkennt und warum sich Marktwerte derselben Karte je Variante unterscheiden (qualitativ, keine Preiszahlen).",
    outline: ["Normal, Holo, Reverse Holo: der sichtbare Unterschied", "Full Art und strukturierte Oberflächen", "Warum dieselbe Karte mehrere Marktwerte hat", "Varianten beim Nachschlagen auf Cardmarket richtig auswählen"],
  },
  {
    slug: "illustration-rare-und-special-illustration-rare",
    title: "Illustration Rare und Special Illustration Rare: Was die modernen Seltenheiten bedeuten",
    icon: "gem",
    badge: "Seltenheit",
    color: "amber",
    headerGradient: "from-amber-700 to-orange-900",
    brief: "Suchintention: \"special illustration rare pokemon\". Die Seltenheitsstufen der Karmesin-&-Purpur-Ära erklären (Illustration Rare, Special Illustration Rare, Hyper Rare, Double Rare, Ultra Rare) und ihre Symbole. Keine erfundenen Druckraten — die sind nicht offiziell veröffentlicht; darauf hinweisen.",
    outline: ["Die Seltenheitsstufen der aktuellen Ära und ihre Symbole", "Was Illustration Rares von anderen Karten unterscheidet", "Warum Druckraten nicht offiziell bekannt sind", "Wie Sammler diese Karten nachschlagen und einordnen"],
  },
  {
    slug: "deutsche-oder-englische-pokemon-karten",
    title: "Deutsche, englische oder japanische Pokémon-Karten: Was die Sprache ausmacht",
    icon: "map",
    badge: "Sprachen",
    color: "blue",
    headerGradient: "from-blue-800 to-blue-950",
    brief: "Suchintention: \"deutsche oder englische pokemon karten wert\". Sachlich einordnen, warum Kartensprachen unterschiedlich gehandelt werden: Auflagenhöhe, internationale Nachfrage, Grading-Markt, Spielbarkeit. Keine Preiszahlen, keine Empfehlung — Kriterien für die eigene Entscheidung.",
    outline: ["Warum dieselbe Karte je Sprache anders gehandelt wird", "Englische Karten und der internationale Markt", "Deutsche Karten: Sammlerperspektive und Besonderheiten", "Japanische Karten: Qualität, Sets und Unterschiede"],
  },
  {
    slug: "pokemon-sammelalbum-binder-richtig-nutzen",
    title: "Sammelalbum und Binder richtig nutzen: Was Karten schützt und was ihnen schadet",
    icon: "book",
    badge: "Aufbewahrung",
    color: "emerald",
    headerGradient: "from-emerald-800 to-green-950",
    brief: "Suchintention: \"pokemon sammelalbum\". Binder-Typen (Ringbuch vs. gebunden, seitlich eingelegte Taschen), Materialfragen (säurefrei, PVC-frei), typische Schäden durch Ringe und Überfüllung, Lagerung. Allgemeine Kriterien, keine Markenempfehlung.",
    outline: ["Ringbuch oder gebundenes Album: der Unterschied für die Karten", "Material: worauf bei Taschen zu achten ist", "Die typischen Schäden — und wie man sie vermeidet", "Welche Karten ins Album gehören und welche nicht"],
  },
  {
    slug: "pokemon-code-karten-erklaert",
    title: "Code-Karten in Pokémon-Boostern: Wofür sie gut sind",
    icon: "card",
    badge: "Grundlagen",
    color: "indigo",
    headerGradient: "from-indigo-800 to-indigo-950",
    brief: "Suchintention: \"pokemon code karten\". Was die Code-Karten in Boostern sind, wofür sie im digitalen Spiel eingelöst werden und ob sie einen Sammelwert haben. Nur Fakten, die auf pokemon.com dokumentiert sind; Verweis auf die offizielle Seite.",
    outline: ["Was eine Code-Karte ist", "Einlösen: der Weg ins digitale Spiel", "Haben Code-Karten einen Wert?", "Häufige Fragen und Missverständnisse"],
  },
  {
    slug: "pokemon-pull-rates-verstehen",
    title: "Pull Rates verstehen: Was man über die Wahrscheinlichkeit seltener Karten weiß",
    icon: "chart",
    badge: "Statistik",
    color: "blue",
    headerGradient: "from-blue-800 to-blue-950",
    brief: "Suchintention: \"pokemon pull rates\". Erklären, was Pull Rates sind, warum sie NICHT offiziell veröffentlicht werden und woher Community-Schätzungen stammen (große Öffnungs-Stichproben). KEINE konkreten Raten nennen oder erfinden. Statistische Grundidee (Erwartungswert, Streuung) verständlich machen.",
    outline: ["Was mit Pull Rates gemeint ist", "Warum es keine offiziellen Zahlen gibt", "Wie Schätzungen entstehen — und wo sie an Grenzen stoßen", "Erwartungswert und Streuung: was das für das Öffnen bedeutet"],
  },
  {
    slug: "pokemon-fehldrucke-misprints",
    title: "Fehldrucke bei Pokémon-Karten: Was ein Misprint ist und was nicht",
    icon: "microscope",
    badge: "Besonderheiten",
    color: "amber",
    headerGradient: "from-amber-700 to-orange-900",
    brief: "Suchintention: \"pokemon fehldruck wert\". Echte Fehldrucke (Fehlschnitt, Farbfehler, fehlende Holo-Schicht, doppelter Druck) von Beschädigungen und Fälschungen abgrenzen. Wie der Markt Fehldrucke behandelt (qualitativ). Keine erfundenen Einzelfälle oder Preise.",
    outline: ["Was als echter Fehldruck gilt", "Beschädigung oder Fehldruck? Die Abgrenzung", "Warum manche Fehldrucke gesucht sind und andere nicht", "Prüfen und dokumentieren"],
  },
  {
    slug: "pokemon-tcg-serien-reihenfolge",
    title: "Alle Pokémon-TCG-Serien in der richtigen Reihenfolge",
    icon: "map",
    badge: "Überblick",
    color: "indigo",
    headerGradient: "from-indigo-800 to-indigo-950",
    brief: "Suchintention: \"pokemon sets reihenfolge\". Die Serien des Sammelkartenspiels in chronologischer Reihenfolge (Base-Ära bis Karmesin & Purpur) mit ihren Hauptmerkmalen. NUR Serien-Namen und Reihenfolge, die auf Bulbapedia dokumentiert sind; keine Erscheinungsdaten erfinden, im Zweifel weglassen.",
    outline: ["Die frühen Serien: Base bis e-Card", "EX, Diamant & Perl, Platin, HeartGold & SoulSilver", "Schwarz & Weiß, XY, Sonne & Mond, Schwert & Schild", "Karmesin & Purpur und wie man sich zurechtfindet"],
  },
  {
    slug: "pokemon-karten-reinigen",
    title: "Pokémon-Karten reinigen: Was geht, und was die Karte ruiniert",
    icon: "shield",
    badge: "Pflege",
    color: "rose",
    headerGradient: "from-rose-800 to-rose-950",
    brief: "Suchintention: \"pokemon karten reinigen\". Sachlich: Staub und Fingerabdrücke vorsichtig entfernen, was man NIE tun sollte (Flüssigkeiten, Radiergummi, Pressen), und warum Eingriffe beim Grading als Manipulation gelten können. Keine Produktempfehlung.",
    outline: ["Was sich gefahrlos entfernen lässt", "Die Methoden, die Karten dauerhaft schaden", "Reinigen vor dem Grading: warum Vorsicht geboten ist", "Vorbeugen ist besser: Handling und Aufbewahrung"],
  },
  {
    slug: "warum-pokemon-karten-preise-schwanken",
    title: "Warum Pokémon-Kartenpreise schwanken: Die Mechanik hinter den Bewegungen",
    icon: "trending",
    badge: "Markt",
    color: "violet",
    headerGradient: "from-violet-800 to-indigo-900",
    brief: "Suchintention: \"warum steigen pokemon karten preise\". Die dokumentierten Einflussgrößen: Neuerscheinungen, Nachdrucke, Turnierrelevanz, Hype-Phasen, Angebotsmenge, Zustand. Einordnung, wie man eine Bewegung liest (einzelner Stand vs. Verlauf, 30-Tage-Schnitt). Keine Preiszahlen, keine Prognose, keine Kaufempfehlung. Verweis auf den CardBeacon Index der Seite.",
    outline: ["Angebot: Nachdrucke, Produktionsende, Menge im Umlauf", "Nachfrage: Neuerscheinungen, Spielbarkeit, Aufmerksamkeit", "Ein Stand ist kein Trend: Bewegungen richtig lesen", "Den Gesamtmarkt einordnen: wozu ein Index dient"],
  },
  {
    slug: "pokemon-nachdrucke-reprints",
    title: "Nachdrucke und Reprints: Was sie für bestehende Karten bedeuten",
    icon: "refresh",
    badge: "Markt",
    color: "emerald",
    headerGradient: "from-emerald-800 to-green-950",
    brief: "Suchintention: \"pokemon reprint\". Was ein Nachdruck ist (erneute Produktion, Neuauflage in Sammlungen, Wiederabdruck einer Karte in einem neuen Set) und das allgemein beobachtete Marktmuster. Keine erfundenen Beispiele mit Preisen.",
    outline: ["Die Formen des Nachdrucks", "Wie der Markt typischerweise reagiert", "Unterschied zwischen Karte und Produkt", "Woran man angekündigte Nachdrucke erkennt"],
  },
  {
    slug: "pokemon-karten-sammeln-anfangen",
    title: "Pokémon-Karten sammeln anfangen: Ein Plan statt Zufallskäufe",
    icon: "rocket",
    badge: "Einsteiger",
    color: "emerald",
    headerGradient: "from-emerald-800 to-green-950",
    brief: "Suchintention: \"pokemon karten sammeln anfangen\". Ein Einstieg mit Ziel: Sammelschwerpunkt wählen (Lieblings-Pokémon, Set, Artwork), Budget festlegen, Einzelkarten vs. Booster, Grundausstattung zur Aufbewahrung. Neutral, keine Kaufempfehlung, keine Preiszahlen.",
    outline: ["Einen Sammelschwerpunkt finden", "Budget und Erwartung festlegen", "Booster öffnen oder Einzelkarten suchen — die Abwägung", "Die Grundausstattung für den Anfang"],
  },
  {
    slug: "pokemon-gold-karten-erklaert",
    title: "Gold-Karten bei Pokémon: Was dahintersteckt",
    icon: "trophy",
    badge: "Seltenheit",
    color: "amber",
    headerGradient: "from-amber-700 to-orange-900",
    brief: "Suchintention: \"pokemon gold karte\". Was mit Gold-Karten gemeint ist (Secret Rares, Hyper Rares mit Goldrahmen, Gold-Metallkarten aus Sonderprodukten) und wie man sie unterscheidet. Hinweis: Metallkarten aus Sonderprodukten sind keine regulären Sammelkarten. Keine Preiszahlen.",
    outline: ["Welche Karten als Gold-Karten bezeichnet werden", "Secret Rare und Hyper Rare: Merkmale", "Metallkarten aus Sonderprodukten: was sie sind", "Gold-Karten nachschlagen und richtig einordnen"],
  },
  {
    slug: "pokemon-karten-flohmarkt-und-kleinanzeigen",
    title: "Pokémon-Karten auf Flohmarkt und Kleinanzeigen kaufen: Worauf achten",
    icon: "search",
    badge: "Kaufen",
    color: "rose",
    headerGradient: "from-rose-800 to-rose-950",
    brief: "Suchintention: \"pokemon karten kleinanzeigen\". Konvolute prüfen, Fälschungen und beschädigte Karten erkennen, realistische Einschätzung vor Ort mit der Preissuche, sicherer Kaufablauf. Keine Preiszahlen, keine Plattformempfehlung.",
    outline: ["Konvolute: was darin typischerweise steckt", "Echtheit und Zustand vor Ort prüfen", "Vor dem Kauf nachschlagen — auch am Handy", "Sicher bezahlen und übergeben"],
  },
  {
    slug: "vintage-oder-moderne-pokemon-karten",
    title: "Vintage oder modern: Wie sich alte und neue Pokémon-Karten unterscheiden",
    icon: "clock",
    badge: "Überblick",
    color: "violet",
    headerGradient: "from-violet-800 to-indigo-900",
    brief: "Suchintention: \"vintage pokemon karten\". Unterschiede in Druck, Auflage, Zustandsverteilung, Grading-Bedeutung und Marktverhalten zwischen WotC-Ära und modernen Sets. Qualitativ, keine Preiszahlen, keine Empfehlung.",
    outline: ["Was als Vintage gilt", "Druck und Material: sichtbare Unterschiede", "Warum der Zustand bei alten Karten so viel ausmacht", "Wie sich die beiden Märkte verhalten"],
  },
  {
    slug: "pokemon-bulk-massenkarten-verkaufen",
    title: "Massenkarten und Bulk: Was man mit tausenden Common-Karten macht",
    icon: "package",
    badge: "Verkaufen",
    color: "blue",
    headerGradient: "from-blue-800 to-blue-950",
    brief: "Suchintention: \"pokemon karten bulk verkaufen\". Realistisch einordnen: Commons/Uncommons haben einzeln kaum Marktwert. Optionen: Sortieren nach Holos und Energie, als Konvolut verkaufen, weitergeben, spielen. Welche Karten man vorher herausziehen sollte. Keine Preiszahlen.",
    outline: ["Warum Massenkarten einzeln kaum gehandelt werden", "Vorher herausziehen: welche Karten nicht in den Bulk gehören", "Als Konvolut verkaufen: Beschreibung und Versand", "Andere Wege: weitergeben, tauschen, spielen"],
  },
];

/** Slugs aller statischen + generierbaren Guides dürfen nicht kollidieren. */
export function getTopicBySlug(slug: string): GuideTopic | undefined {
  return GUIDE_TOPICS.find((t) => t.slug === slug);
}
